@startuml
skinparam classAttributeIconSize 0
class PaymentScheduleViewComponent
class RecordPaymentDialogComponent
class ScheduleAdjustmentDialogComponent
class ReversePaymentDialogComponent
class PaymentHistoryViewComponent
class PaymentService

PaymentScheduleViewComponent --> PaymentService
RecordPaymentDialogComponent --> PaymentService
ScheduleAdjustmentDialogComponent --> PaymentService
ReversePaymentDialogComponent --> PaymentService
PaymentHistoryViewComponent --> PaymentService
@enduml
