@startuml
skinparam classAttributeIconSize 0
class PaymentScheduleView <<razor>>
class RecordPaymentDialog <<razor>>
class ScheduleAdjustmentDialog <<razor>>
class ReversePaymentDialog <<razor>>
class PaymentHistoryView <<razor>>
interface IPaymentService

PaymentScheduleView --> IPaymentService
RecordPaymentDialog --> IPaymentService
ScheduleAdjustmentDialog --> IPaymentService
ReversePaymentDialog --> IPaymentService
PaymentHistoryView --> IPaymentService
@enduml
