@startuml
skinparam classAttributeIconSize 0
class UserListComponent
class AddEditUserDialogComponent
class RoleManagementComponent
class AuditEventPanelComponent
class BorrowerDirectorySelectComponent
class UserService

UserListComponent --> UserService
AddEditUserDialogComponent --> UserService
RoleManagementComponent --> UserService
AuditEventPanelComponent --> UserService
BorrowerDirectorySelectComponent --> UserService
@enduml
