@startuml
skinparam classAttributeIconSize 0
class CustomAuthStateProvider
class CascadingAuthenticationState
class LoginPage <<razor>>
class SignUpPage <<razor>>
class VerifyEmailPage <<razor>>
class SessionExpiredDialog <<razor>>
interface IAuthService

CascadingAuthenticationState --> CustomAuthStateProvider
LoginPage --> IAuthService
SignUpPage --> IAuthService
VerifyEmailPage --> IAuthService
SessionExpiredDialog --> CustomAuthStateProvider
@enduml
