@startuml
skinparam classAttributeIconSize 0
class NotificationBellComponent
class NotificationDropdownComponent
class NotificationListComponent
class NotificationStreamService
class SnackBarService
class PreferencesComponent
class NotificationService

NotificationBellComponent --> NotificationStreamService
NotificationDropdownComponent --> NotificationService
NotificationListComponent --> NotificationService
NotificationStreamService --> NotificationService
PreferencesComponent --> NotificationService
SnackBarService --> NotificationStreamService
@enduml
