@startuml
skinparam classAttributeIconSize 0
class AuthService
class AuthGuard
class LoginComponent
class SignUpComponent
class VerifyEmailComponent
class SessionExpiredDialogComponent
class AuthApi

AuthGuard --> AuthService
LoginComponent --> AuthApi
SignUpComponent --> AuthApi
VerifyEmailComponent --> AuthApi
SessionExpiredDialogComponent --> AuthService
@enduml
